#!/bin/bash

# Script để setup environment variables cho Supabase

echo "🚀 Setup Supabase Environment Variables"
echo ""

# Kiểm tra xem file .env đã tồn tại chưa
if [ -f .env ]; then
    echo "⚠️  File .env đã tồn tại."
    read -p "Bạn có muốn ghi đè không? (y/n): " overwrite
    if [ "$overwrite" != "y" ]; then
        echo "❌ Hủy bỏ."
        exit 0
    fi
fi

echo ""
echo "📝 Vui lòng nhập thông tin Supabase:"
echo ""

# Nhập Supabase URL
read -p "Supabase Project URL (ví dụ: https://abc123.supabase.co): " SUPABASE_URL

# Validate URL
if [[ ! $SUPABASE_URL =~ ^https://.*\.supabase\.co$ ]]; then
    echo "⚠️  URL không đúng định dạng. Ví dụ: https://abc123.supabase.co"
    read -p "Bạn vẫn muốn tiếp tục? (y/n): " continue
    if [ "$continue" != "y" ]; then
        exit 1
    fi
fi

# Nhập Anon Key
read -p "Supabase Anon Key: " SUPABASE_ANON_KEY

# Tạo file .env
cat > .env << EOF
# Supabase Configuration
# Generated by setup script on $(date)

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
EOF

echo ""
echo "✅ Đã tạo file .env thành công!"
echo ""
echo "📋 Thông tin đã lưu:"
echo "   URL: $SUPABASE_URL"
echo "   Anon Key: ${SUPABASE_ANON_KEY:0:20}..."
echo ""
echo "💡 Lưu ý: File .env đã được thêm vào .gitignore và sẽ không được commit vào git."
echo ""
echo "🔄 Bây giờ bạn có thể chạy: npm run dev"

